### ISSUE TITLE
Some chapters with pages less than 3 load infinitely for non-existing pages.

### ISSUE THREAD

**Issue by KrisCris** [hanerx/flutter_dmzj#11]
**Describe the bug**
Some chapters with pages less than 3 load infinitely for non-existing pages.

Edit: And I have to manually select the next chapter

**Expected behavior**
Remove those loading icons and show the existing pages only.

**Version**
From https://github.com/hanerx/flutter_dmzj/actions/runs/279847998

**Screenshot**
![Screenshot_20201002-133801](https://user-images.githubusercontent.com/38860226/94938899-0497d700-0504-11eb-90a9-f668b06b4116.jpg)

**Comment by hanerx** [comment]
单个页面会导致上下话加载问题，提供上一话下一话按钮手动进行加载解决
