### ISSUE TITLE
关于翻页动画

### ISSUE THREAD

**Issue by ChellyL** [hanerx/flutter_dmzj#21]
app现在的翻页动画（？）为左右滑行，能否增加“无翻页动画”的选项？
在墨水屏阅读器上使用app看漫画时，如果有翻页动画，屏幕刷新跟不上，会有点瞎眼……

**Comment by hanerx** [comment]
现在只实现了横向阅读的禁用动画，而且需要使用点击翻页而不是拖动翻页，音量键翻页也支持禁用动画
